---
title: "Fox_Insect_Abundances"
author: "Rachel Fox"
date: "May 22, 2015"
output: html_document
runtime: shiny
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(BH))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(rgdal))
suppressPackageStartupMessages(library(rgeos))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(rvest))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(maps))
suppressPackageStartupMessages(library(maptools))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(require(gridExtra))
gpclibPermit()

#Insect Counts and Timeseries
insectcount<- read.csv("./Data/insectcounts_na.csv", header=TRUE) %>%
              tbl_df() %>% 
              gather(family,n, 5:68) %>%
              mutate(date=mdy(date)) %>%
              transmute(date, bottle.name, location, trap.name, family, n)

#Timeseries- Weather
weather1<- read.csv("./Data/weatherdata.txt") %>% tbl_df() %>%
           mutate(date= ymd(Date))%>% 
          select(date, TemperatureAvgF)

weather <- read.csv("./Data/insect_weather.csv") %>% tbl_df %>%
            unite(Date, year,dayofyear, sep = "-") %>%
            transmute(date=parse_date_time(Date, "%y%j"),TemperatureAvgF=TemperatureAvgF) %>%
            bind_rows(weather1)
          

#Combining Insects with Trap Locations.
traplocations <- read.csv("./Data/traplocations.csv",header=TRUE) %>%
                 tbl_df()
locationcoord <- read.csv("./Data/locationzoom.csv", header=TRUE) %>%
                 tbl_df()

insects <- insectcount %>% 
                group_by(date, trap.name, family) %>%
                summarise(count=sum(n))
insectloc <- inner_join(insects, traplocations, by="trap.name") %>%
                tbl_df() 


# for total abundance timeseries
insectsum <- insectcount %>% 
             group_by(date, family) %>%
             summarise(count=sum(n))
     
#Extracting data and creating data for plotting

##Vegetation
jr.vegfile <- readOGR(dsn="./Data/JRVEG_SHAPEFILE", layer="JR_vegetation_2012", 
              verbose=FALSE) %>%
              spTransform(CRS("+proj=longlat +ellps=WGS84")) 

jr.vegfile@data$id = rownames(jr.vegfile@data)

veg.map <- fortify(jr.vegfile, region="id") %>% tbl_df()
veg.df <- inner_join(veg.map, jr.vegfile@data, by="id") %>%
          filter(CNDDB1 %in% c("Bog and Marsh", "Broad Leafed Upland Tree Dominated", "Coniferous Upland Forest and Woodland", "Grass and Herb Dominated Communities", "Riparian and Bottomland Habitat", "Scrub and Chaparral")) %>%
          rename(Vegetation=CNDDB1)

#Overall Map
#google map access
google.map <-
  get_map(location = "Searsville Lake, San Mateo County, CA", maptype = "hybrid", zoom = 15, color = "color")


```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
inputPanel(
  dateRangeInput("daterange", "Date range:",
               start = "2012-05-30",
               end   = "2013-07-10",
               format = "MM-dd-yy",
               min = "2012-05-30",
               max = "2013-07-10"
               ),
  
  selectInput("family", label = "Insect Family",
               choices = c("total.count", "s.acalyptrata", "acalyptrata", "s.calyptrata", "calyptrata", "auchenorrhynca", "o.auchenorrhyncha", "polyphaga", "o.polyphaga", 
"s.apocrita", "apocrita", "o.apocrita", "p.apocrita", "formicidae", 
"vespidae", "anthrophila", "chironomidae", "o.chironomidae", 
"sciaridae", "mycetophilidae", "o.mycetophilidae", "cecydomidae", 
"empidoidea", "o.empidoidea", "platypezidae", "phoroidea", "o.phoroi", 
"sternorrhyca", "o.sternorrhyncha", "psocoptera", "odonata", 
"syrphoidia", "o.syrphoidea", "s.lepidoptera", "lepidoptera", 
"o.lepidoptera", "lepidoptera.2", "psychodomorpha", "neuroptera", 
"tipulomorpha", "o.tipulomorpha", "heteroptera", "o.heterop", 
"tingidae", "plannipenia", "o.plannipenia", "tricoptera", "o.tricoptera", 
"symphyta", "ceratopogonidae", "xylophagomorpha", "tabanomorpha", 
"thysanoptera", "scathophagidae", "ephemeridae", "asilidae", 
"culicidae", "isoptera", "simuliidae", "lonchopteridae", "plecoptera", 
"rophidoptera", "dolichopodidae"), selected = "total.count", multiple= TRUE
  ),

submitButton("Submit")
)

output$plot<-renderPlot({
      # Inputs and Variables.    
      startdate <- input$daterange[1]
      enddate <- input$daterange[2]
      date.range <- interval(startdate, enddate)
      
      familynames <- input$family
   
      insectgraph <- filter(insectloc, family %in% familynames ) %>%
                     filter(date %within% date.range)
      
      insecttime <- filter(insectsum, family %in% familynames) %>%
                    filter(date %within% date.range)
      
      weather <- filter(weather, date %within% date.range)
 
      
# Make map.  
map <-  ggmap(google.map)+
        geom_polygon(data=veg.df, 
                     aes(x=long, y=lat, group=group, fill=Vegetation),alpha=0.2) +
        geom_point(data=insectgraph, 
                     aes(x=long, y=lat, size=count, color=family), alpha=0.5)+
        scale_color_brewer(palette="Set1")+
        scale_size_continuous(range = c(1, 18))+
        coord_map() +
        xlab("Longitude") + ylab("Latitude")+
        theme_bw()
  
#Timeseries
i.timeseries <- ggplot(insecttime, aes(x=date, y=count, col= family))+
                geom_line()+
                scale_color_brewer(palette="Set1")+
                xlab("Date") + ylab("Insect Abundance (Count)")+
                ggtitle(paste(paste("Insect Abundance from", startdate, "to", enddate))) +
                theme_minimal()+
                theme(legend.position = "none")

w.timeseries <- ggplot(weather, aes(x=date, y=TemperatureAvgF)) +
                geom_line() +
                xlab("Date") + ylab("Avg. Temperature in F˚")+
                ggtitle(paste(paste("Average Temperature from", startdate, "to", enddate)))+
                theme_minimal()


               grid.newpage() 
      pushViewport(viewport(layout = grid.layout(9, 1)))
      print(map, vp = viewport(layout.pos.row = 1:5, layout.pos.col = 1))
      print(i.timeseries, vp = viewport(layout.pos.row = 6:7, layout.pos.col = 1)) 
      print(w.timeseries, vp = viewport(layout.pos.row = 8:9, layout.pos.col = 1)) 
      
    }, height = 800, width = 800 )

# Use this for no table
plotOutput("plot", height="auto")
```
